version: "3"

services:
  user_service:
    build: ./user-service
    restart: always
    expose:
      - ${USER_SERVICE_PORT}
    environment:
      PORT: ${USER_SERVICE_PORT}
      ISSUER_URI: ${JWT_ISSUER_URI}
      USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      USER_POOL_CLIENT_ID: ${COGNITO_USER_POOL_CLIENT_ID}
      USER_POOL_CLIENT_SECRET: ${COGNITO_USER_POOL_CLIENT_SECRET}
      S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_ACCESS_KEY: ${AWS_USER_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_USER_SECRET_KEY}
    networks:
      - main

  product_service:
    build: ./product-service
    restart: always
    expose:
      - ${PRODUCT_SERVICE_PORT}
    links:
      - user_service:user-service
    depends_on:
      user_service:
        condition: service_started
    environment:
      PORT: ${PRODUCT_SERVICE_PORT}
      ISSUER_URI: ${JWT_ISSUER_URI}
      S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_ACCESS_KEY: ${AWS_USER_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_USER_SECRET_KEY}
      USER_SERVICE_HOST: user-service
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
    networks:
      - main

  order_service:
    build: ./order-service
    restart: always
    expose:
      - ${ORDER_SERVICE_PORT}
    links:
      - user_service:user-service
      - product_service:product-service
    depends_on:
      - user_service
      - product_service
    environment:
      PORT: ${ORDER_SERVICE_PORT}
      ISSUER_URI: ${JWT_ISSUER_URI}
      AWS_ACCESS_KEY: ${AWS_USER_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_USER_SECRET_KEY}
      USER_SERVICE_HOST: user-service
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      PRODUCT_SERVICE_HOST: product-service
      PRODUCT_SERVICE_PORT: ${PRODUCT_SERVICE_PORT}
    networks:
      - main
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    links:
      - user_service:user-service
      - product_service:product-service
      - order_service:order-service
    depends_on:
      - user_service
      - product_service
      - order_service
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - main
    
networks:
  main:
    driver: bridge
