package com.nebulamart.orderservice.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "order")
public class Order {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String productId;
    @DynamoDBAttribute
    private String productName;
    @DynamoDBAttribute
    private String customerId;
    @DynamoDBAttribute
    private String customerName;
    @DynamoDBAttribute
    private String sellerId;
    @DynamoDBAttribute
    private String sellerName;
    @DynamoDBAttribute
    private String courierId;
    @DynamoDBAttribute
    private String courierName;

    @DynamoDBAttribute
    private List<Float> dispatchLocation;
    @DynamoDBAttribute
    private List<Float> deliveryLocation;
    @DynamoDBAttribute
    private String dispatchDate;
    @DynamoDBAttribute
    private String deliveryDate;
    @DynamoDBAttribute
    private String status;

}
