package com.nebulamart.productservice.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "review")
public class Review {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String productId;
    @DynamoDBAttribute
    private String productName;
    @DynamoDBAttribute
    private String orderId;
    @DynamoDBAttribute
    private String customerId;
    @DynamoDBAttribute
    private String customerName;
    @DynamoDBAttribute
    private String description;
    @DynamoDBAttribute
    private int productRating;
    @DynamoDBAttribute
    private int courierRating;

}
